import mopy.model

from mopy.model import mo___AnalogSignal as AnalogSignal
from mopy.model import mo___Arrangement as Arrangement
from mopy.model import mo___Arranger as Arranger
from mopy.model import mo___AudioFile as AudioFile
from mopy.model import mo___CD as CD
from mopy.model import mo___Composer as Composer
from mopy.model import mo___Composition as Composition
from mopy.model import mo___Conductor as Conductor
from mopy.model import mo___CorporateBody as CorporateBody
from mopy.model import mo___DAT as DAT
from mopy.model import mo___DCC as DCC
from mopy.model import mo___DVDA as DVDA
from mopy.model import mo___DigitalSignal as DigitalSignal
from mopy.model import mo___ED2K as ED2K
from mopy.model import mo___Festival as Festival
from mopy.model import mo___Genre as Genre
from mopy.model import mo___Instrument as Instrument
from mopy.model import mo___Instrumentation as Instrumentation
from mopy.model import mo___Label as Label
from mopy.model import mo___Libretto as Libretto
from mopy.model import mo___Listener as Listener
from mopy.model import mo___Lyrics as Lyrics
from mopy.model import mo___MD as MD
from mopy.model import mo___MagneticTape as MagneticTape
from mopy.model import mo___Medium as Medium
from mopy.model import mo___Movement as Movement
from mopy.model import mo___MusicArtist as MusicArtist
from mopy.model import mo___MusicGroup as MusicGroup
from mopy.model import mo___MusicalExpression as MusicalExpression
from mopy.model import mo___MusicalItem as MusicalItem
from mopy.model import mo___MusicalManifestation as MusicalManifestation
from mopy.model import mo___MusicalWork as MusicalWork
from mopy.model import mo___Orchestration as Orchestration
from mopy.model import mo___Performance as Performance
from mopy.model import mo___Performer as Performer
from mopy.model import mo___PublishedLibretto as PublishedLibretto
from mopy.model import mo___PublishedLyrics as PublishedLyrics
from mopy.model import mo___PublishedScore as PublishedScore
from mopy.model import mo___Record as Record
from mopy.model import mo___Recording as Recording
from mopy.model import mo___ReleaseStatus as ReleaseStatus
from mopy.model import mo___ReleaseType as ReleaseType
from mopy.model import mo___SACD as SACD
from mopy.model import mo___Score as Score
from mopy.model import mo___Show as Show
from mopy.model import mo___Signal as Signal
from mopy.model import mo___SoloMusicArtist as SoloMusicArtist
from mopy.model import mo___Sound as Sound
from mopy.model import mo___SoundEngineer as SoundEngineer
from mopy.model import mo___Stream as Stream
from mopy.model import mo___Torrent as Torrent
from mopy.model import mo___Track as Track
from mopy.model import mo___Vinyl as Vinyl
from mopy.model import mo___bootleg as bootleg
from mopy.model import mo___official as official
from mopy.model import mo___promotion as promotion
from mopy.model import mo___album as album
from mopy.model import mo___audiobook as audiobook
from mopy.model import mo___compilation as compilation
from mopy.model import mo___ep as ep
from mopy.model import mo___interview as interview
from mopy.model import mo___live as live
from mopy.model import mo___remix as remix
from mopy.model import mo___soundtrack as soundtrack
from mopy.model import mo___spokenword as spokenword
